title: Anvay's CompSci Blog
description: "August 2023 to June 2024"
owner_name: Anvay Vahia
github_username: CyberLord09
github_repo: "AnvayDNHSCompSci"
baseurl: "/AnvayDNHSCompSci"
remote_theme: jekyll/minima
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/nighthawkcoders"}
    - { platform: github, user_url: "https://github.com/CyberLord09"}
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
